
# project dependncies

# Library
ADD_DEPENDENCIES(CVLBaseLib CVLLogLib)
ADD_DEPENDENCIES(CVLIOLib CVLBaseLib)
ADD_DEPENDENCIES(CVLSGMLib CVLBaseLib CVLIOLib)
ADD_DEPENDENCIES(CVLWrapLib CVLBaseLib)

# Application
IF(BUILD_SAMPLES)
    ADD_DEPENDENCIES(SGMApp CVLSGMLib)
ENDIF()

# Test
IF(BUILD_UNIT_TESTS)
    ADD_DEPENDENCIES(TestLog CVLLogLib)
ENDIF()