FILE(GLOB SGM_INCLUDE_FILES 
"${PROJECT_SOURCE_DIR}/src/sgm/sgm.h")

FILE(GLOB BASE_INCLUDE_FILES 
"${PROJECT_SOURCE_DIR}/src/base/*.h" "${PROJECT_SOURCE_DIR}/src/base/*.inl")

INSTALL(FILES ${SGM_INCLUDE_FILES}
 DESTINATION ${CMAKE_INSTALL_PREFIX}/include/sgm)
 
INSTALL(FILES ${BASE_INCLUDE_FILES}
 DESTINATION ${CMAKE_INSTALL_PREFIX}/include/base)
