
# SGM
FILE(GLOB SGM_INCLUDE_FILES 
"${PROJECT_SOURCE_DIR}/src/sgm/sgm.h")
INSTALL(FILES ${SGM_INCLUDE_FILES}
 DESTINATION ${CMAKE_INSTALL_PREFIX}/include/sgm)

# BASE
FILE(GLOB BASE_INCLUDE_FILES 
"${PROJECT_SOURCE_DIR}/src/base/*.h" "${PROJECT_SOURCE_DIR}/src/base/*.inl") 
INSTALL(FILES ${BASE_INCLUDE_FILES}
 DESTINATION ${CMAKE_INSTALL_PREFIX}/include/base)
 
# IO
FILE(GLOB IO_INCLUDE_FILES 
"${PROJECT_SOURCE_DIR}/src/base/*.h" "${PROJECT_SOURCE_DIR}/src/base/*.inl") 
INSTALL(FILES ${BASE_INCLUDE_FILES}
 DESTINATION ${CMAKE_INSTALL_PREFIX}/include/io)
 
# TIME
FILE(GLOB TIME_INCLUDE_FILES 
"${PROJECT_SOURCE_DIR}/src/time/*.h" "${PROJECT_SOURCE_DIR}/src/base/*.inl") 
INSTALL(FILES ${BASE_INCLUDE_FILES}
 DESTINATION ${CMAKE_INSTALL_PREFIX}/include/time)
